sudo: false
language: node_js
cache: yarn
node_js:
  - '10'
  - '8'
  - '6'
script:
  - ./script/lint-commits
  - ./script/prettier-check
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: npm release
      node_js: '8'
      script:
        - echo "Deploying to npm…"
        - yarn add --dev semantic-release
        - yarn semantic-release
