sudo: false
language: node_js
node_js:
  - '10'
  - '8'
  - '6'
script:
  - ./script/lint-commits
  - ./script/prettier-check
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: npm release
      node_js: '8'
      script:
        - echo "Deploying to npm…"
        - npx semantic-release
