sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
script:
  - ./script/lint-commits
  - ./script/prettier-check
  - yarn test
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
